markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: 杨雍的博客
    description: Cocos2d-x核心开发者兼游戏制作人
    title: 杨雍的博客
    url: http://ivenyang.com/
    duoshuo: Ivenyang
    tongji: <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?99dd06de5dba3aa89e08ee5d9e733280";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
    qiniu:1
author:
    name:杨雍
    email: 1@q.com
    weibo:    http://weibo.com/1
    github:   http://github.com/ivenyang
    logo:https://raw.githubusercontent.com/Ivenyang/Ivenyang.github.io/master/res/img/logo.png                                             # logo地址
    douban:1
        name: 1
        key: 1